### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ritschwumm**

### CODE REVIEW

**Comment by tpolecat** [comment]
Thanks! Build is busted but I'll get it sorted.

**Comment by tpolecat** [comment]
You didn't break it, I did.

**Comment by tpolecat** [comment]
I'll merge this if you re-open, sorry. I haven't had a chance to look at this project in a few days.

**Comment by tpolecat** [comment]
Actually I can do it.

**Comment by ritschwumm** [comment]
sorry, somehow i thought you already incorporated the change without merging my PR.

**Pull request merged**
